openapi: 3.0.1
info:
  title: Sales API
  description: Aplicacion para la prueba de desarrollo de Quick. Sistema de ventas
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://127.0.0.1:8000/
paths:
  /api/users/login/:
    post:
      tags:
      - Auth
      summary: Logueo del usuario, genera token JWT
      requestBody:
        description: Status values that need to be considered for filter
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Token definido
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      x-codegen-request-body-name: body
  /api/users/:
    post:
      tags:
      - Users
      summary: Crear usuario
      requestBody:
        description: Data con informacion del usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Usuario creado correctamente
          content: {}
      x-codegen-request-body-name: body
  /api/sales/clients:
    get:
      tags:
      - Clients
      summary: Lista de clientes creados
      responses:
        200:
          description: Lista
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
      security:
      - sales_auth:
        - admin
    post:
      tags:
      - Clients
      summary: Crear clientes
      requestBody:
        description: Data con informacion del cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        200:
          description: Cliente creado correctamente
          content: {}
        404:
          description: Ya existe un cliente con el documento
          content: {}
      security:
      - sales_auth:
        - admin
      x-codegen-request-body-name: body
  /api/sales/client/{clientId}:
    put:
      tags:
      - Clients
      summary: Editar un cliente por Id
      parameters:
      - name: clientId
        in: path
        description: id del cliente a modificar
        required: true
        schema:
          type: number
      requestBody:
        description: Data con informacion del cliente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        200:
          description: Cliente Actualizado
          content: {}
        404:
          description: No se encuentra el cliente
          content: {}
      security:
      - sales_auth:
        - admin
      x-codegen-request-body-name: body
    delete:
      tags:
      - Clients
      summary: Eliminar un cliente por Id
      parameters:
      - name: clientId
        in: path
        description: id cliente a eliminar
        required: true
        schema:
          type: number
      responses:
        200:
          description: Cliente Eliminado
          content: {}
        404:
          description: No se encuentra el cliente
          content: {}
      security:
      - sales_auth:
        - admin
  /api/clients/export:
    get:
      tags:
      - Clients
      summary: Descargar archivo csv con la data de los clientes
      responses:
        200:
          description: Ok
          content:
            text/csv:
              example: |
                documento,Nombre completo, cantidad de facturas
                5462, surtimax sas, 5
      security:
      - sales_auth:
        - admin
  /api/clients/import:
    post:
      tags:
      - Clients
      summary: Crear clientes por un archivo csv
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                upfile:
                  type: string
                  description: The file to upload.
                  format: binary
      responses:
        200:
          description: Ok
          content: {}
      security:
      - sales_auth:
        - admin
  /api/sales/bills:
    get:
      tags:
      - Bills
      summary: Lista de facturas creadas
      responses:
        200:
          description: Lista
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bill'
      security:
      - sales_auth:
        - admin
    post:
      tags:
      - Bills
      summary: Crear facturas
      requestBody:
        description: Data con informacion de la factura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bill'
        required: true
      responses:
        200:
          description: Factura creada correctamente
          content: {}
      security:
      - sales_auth:
        - admin
      x-codegen-request-body-name: body
  /api/sales/bills/{id}:
    put:
      tags:
      - Bills
      summary: Editar una factura por Id
      parameters:
      - name: id
        in: path
        description: id de la factura a modificar
        required: true
        schema:
          type: number
      requestBody:
        description: Data con informacion de la factura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bill'
        required: true
      responses:
        200:
          description: Factura Actualizada
          content: {}
        404:
          description: No se encuentra la factura
          content: {}
      security:
      - sales_auth:
        - admin
      x-codegen-request-body-name: body
    delete:
      tags:
      - Bills
      summary: Eliminar una factura por Id
      parameters:
      - name: id
        in: path
        description: id de la factura a eliminar
        required: true
        schema:
          type: number
      responses:
        200:
          description: Factura Eliminada
          content: {}
        404:
          description: No se encuentra la factura
          content: {}
      security:
      - sales_auth:
        - admin
  /api/sales/products:
    get:
      tags:
      - Products
      summary: Lista de productos creados
      responses:
        200:
          description: Lista
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
      security:
      - sales_auth:
        - admin
    post:
      tags:
      - Products
      summary: Crear producto
      requestBody:
        description: Data con informacion del producto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        200:
          description: Producto creado correctamente
          content: {}
      security:
      - sales_auth:
        - admin
      x-codegen-request-body-name: body
  /api/sales/products/{id}:
    put:
      tags:
      - Products
      summary: Editar un producto por Id
      parameters:
      - name: id
        in: path
        description: id del producto a modificar
        required: true
        schema:
          type: number
      requestBody:
        description: Data con informacion del producto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        200:
          description: Producto Actualizado
          content: {}
        404:
          description: No se encuentra el producto
          content: {}
      security:
      - sales_auth:
        - admin
      x-codegen-request-body-name: body
    delete:
      tags:
      - Products
      summary: Eliminar un producto por Id
      parameters:
      - name: id
        in: path
        description: id del producto a eliminar
        required: true
        schema:
          type: number
      responses:
        200:
          description: Producto Eliminado
          content: {}
        404:
          description: No se encuentra el producto
          content: {}
      security:
      - sales_auth:
        - admin
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Client:
      type: object
      properties:
        id:
          type: integer
        document:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
    Bill:
      type: object
      properties:
        id:
          type: integer
        company_name:
          type: string
        nit:
          type: string
        code:
          type: string
        client_id:
          type: integer
        products:
          type: array
          items:
            type: integer
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
  securitySchemes:
    sales_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
