swagger: "2.0"
info:
  description: "Aplicacion para la prueba de desarrollo de Quick. Sistema de ventas"
  version: "1.0.0"
  title: "Sales API"
host: "127.0.0.1:8000"
basePath: "/"
schemes:
- "http"
paths:
  /api/users/login/:
    get:
      tags:
      - "Auth"
      summary: "Logueo del usuario, genera token JWT"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Status values that need to be considered for filter"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Token definido"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
  /api/users/:
    post:
      tags:
      - "Users"
      summary: "Crear usuario"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data con informacion del usuario"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Usuario creado correctamente"

  /api/sales/clients:
    get:
      tags:
      - "Clients"
      summary: "Lista de clientes creados"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Lista"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Client"
      security:
      - sales_auth:
        - "admin"
    post:
      tags:
      - "Clients"
      summary: "Crear clientes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data con informacion del cliente"
        required: true
        schema:
          $ref: "#/definitions/Client"
      responses:
        "200":
          description: "Cliente creado correctamente"
        "404":
          description: "Ya existe un cliente con el documento"
      security:
      - sales_auth:
        - "admin"

  /api/sales/client/{clientId}:
    put:
      tags:
      - "Clients"
      summary: "Editar un cliente por Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "clientId"
        type: "number"
        description: "id del cliente a modificar"
        required: true
      - in: "body"
        name: "body"
        description: "Data con informacion del cliente"
        required: true
        schema:
          $ref: "#/definitions/Client"
      responses:
        "200":
          description: "Cliente Actualizado"
        "404":
          description: "No se encuentra el cliente"
      security:
      - sales_auth:
        - "admin"
    delete:
      tags:
      - "Clients"
      summary: "Eliminar un cliente por Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "clientId"
        type: "number"
        description: "id cliente a eliminar"
        required: true
      responses:
        "200":
          description: "Cliente Eliminado"
        "404":
          description: "No se encuentra el cliente"
      security:
      - sales_auth:
        - "admin"

  /api/clients/export:
    get:
      tags:
      - "Clients"
      summary: "Descargar archivo csv con la data de los clientes"
      produces:
        - text/csv
      responses:
        "200":
          description: "Ok"
          examples:
            text/csv: >
              documento,Nombre completo, cantidad de facturas

              5462, surtimax sas, 5
      security:
      - sales_auth:
        - "admin"
  /api/clients/import:
    post:
      tags:
      - "Clients"
      summary: "Crear clientes por un archivo csv"
      consumes:
         - multipart/form-data
      parameters:
       - in: formData
         name: upfile
         type: file
         description: The file to upload.
      responses:
        "200":
          description: "Ok"
      security:
      - sales_auth:
        - "admin"

  /api/sales/bills:
    get:
      tags:
        - "Bills"
      summary: "Lista de facturas creadas"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Lista"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Bill"
      security:
      - sales_auth:
        - "admin"
    post:
      tags:
      - "Bills"
      summary: "Crear facturas"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data con informacion de la factura"
        required: true
        schema:
          $ref: "#/definitions/Bill"
      responses:
        "200":
          description: "Factura creada correctamente"

      security:
      - sales_auth:
        - "admin"

  /api/sales/bills/{id}:
    put:
      tags:
      - "Bills"
      summary: "Editar una factura por Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "number"
        description: "id de la factura a modificar"
        required: true
      - in: "body"
        name: "body"
        description: "Data con informacion de la factura"
        required: true
        schema:
          $ref: "#/definitions/Bill"
      responses:
        "200":
          description: "Factura Actualizada"
        "404":
          description: "No se encuentra la factura"
      security:
      - sales_auth:
        - "admin"
    delete:
      tags:
      - "Bills"
      summary: "Eliminar una factura por Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "number"
        description: "id de la factura a eliminar"
        required: true
      responses:
        "200":
          description: "Factura Eliminada"
        "404":
          description: "No se encuentra la factura"
      security:
      - sales_auth:
        - "admin"

  /api/sales/products:
    get:
      tags:
        - "Products"
      summary: "Lista de productos creados"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Lista"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
      security:
      - sales_auth:
        - "admin"
    post:
      tags:
      - "Products"
      summary: "Crear producto"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Data con informacion del producto"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Producto creado correctamente"

      security:
      - sales_auth:
        - "admin"

  /api/sales/products/{id}:
    put:
      tags:
      - "Products"
      summary: "Editar un producto por Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "number"
        description: "id del producto a modificar"
        required: true
      - in: "body"
        name: "body"
        description: "Data con informacion del producto"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Producto Actualizado"
        "404":
          description: "No se encuentra el producto"
      security:
      - sales_auth:
        - "admin"
    delete:
      tags:
      - "Products"
      summary: "Eliminar un producto por Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: "number"
        description: "id del producto a eliminar"
        required: true
      responses:
        "200":
          description: "Producto Eliminado"
        "404":
          description: "No se encuentra el producto"
      security:
      - sales_auth:
        - "admin"


securityDefinitions:
  sales_auth:
    type: "oauth2"
    tokenUrl: "http://localhost:8000/api/users/login/"
    flow: "password"
    scopes:
      admin: grants
definitions:
  User:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  Client:
    type: "object"
    properties:
      id:
        type: "integer"
      document:
        type: "string"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"
        format: "email"
  Bill:
    type: "object"
    properties:
      id:
        type: "integer"
      company_name:
        type: "string"
      nit:
        type: "string"
      code:
        type: "string"
      client_id:
        type: "integer"
      products:
        type: "array"
        items:
          type: integer
  Product:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"


externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"